---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: Asia/Shanghai
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Android 加油站"
keywords:    "Android, Resource, Open Source, Share"
description: "An Android Grocery Store"
source_link: "https://github.com/tedxiong/tedxiong.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-71746678-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#f8f8f8'
  white:     '#f8f8f8'
  blue:      '#f8f8f8'
  green:     '#f8f8f8'
  purple:    '#f8f8f8'
  orange:    '#f8f8f8'
  turquoise: '#f8f8f8'

kramdown:
  auto_ids:  false

